# general format
format = '$shell$all'

# don't print a new line at the start of the prompt
add_newline = false

# prompt character
[character]     
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

[shell]
zsh_indicator = '\[Z\]'
bash_indicator = '\[\$\]'
powershell_indicator = '\[_\]'
unknown_indicator = '\[?\]'
style = 'bold yellow'
disabled = false
